---
- name: Create influxdb.conf
  template:
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
    backup: true
  notify:
    - Restart influxdb

- name: Start and Enable influxdb service
  service:
    name: influxdb
    state: started
    enabled: true